#!/usr/bin/env python


from belaster.engine.application_context import ApplicationContext
from belaster.engine.application_context_binder import ApplicationContextBinder
from belaster.engine.belaster_file import BELASTER_FILE_DEFAULT_NAME, import_belaster_file, is_belaster_file_path, make_belaster_file_path
from belaster.engine.default_behaviour import OPTIONS_BELASTER_FILE, OPTIONS_HELP, OPTIONS_VERSION, RETURN_CODE_OK, RETURN_CODE_MISSING_BELASTER_FILE
from belaster.engine.mute_stdout import MuteStdout
from enum import Enum
from os import getcwd
from pathlib import Path
from sys import argv



argc_of_belaster = int(argv[1])
argv_of_belaster = argv[2:]


class BashCompleterCase(Enum):
	TARGETS_OPTIONS = 1
	DIRECTORY = 2


result = []



# Default behaviour of belaster.

# Default User Belaster file path.
belaster_path = getcwd() + "/" + BELASTER_FILE_DEFAULT_NAME


if len(argv_of_belaster) <= 2 and argc_of_belaster <= 1:
	result += OPTIONS_BELASTER_FILE + OPTIONS_HELP + OPTIONS_VERSION

elif len(argv_of_belaster) in [2, 3] and argc_of_belaster == 2 \
		and argv_of_belaster[1] in OPTIONS_BELASTER_FILE:
	print(BashCompleterCase.DIRECTORY.value)
	exit(RETURN_CODE_OK)



if len(argv_of_belaster) >= 2 and argv_of_belaster[1] in OPTIONS_BELASTER_FILE \
		and argc_of_belaster >= 3 and is_belaster_file_path(argv_of_belaster[2]):
	belaster_path=make_belaster_file_path(argv_of_belaster[2])
	with open("flibidi.txt", "a") as f:
		f.write("[" + " ".join(argv) + "]\n")



with open("flibidi.txt", "a") as f:
	f.write(f"belaster_path={belaster_path}\n")



if not Path(belaster_path).is_file():
	with open("flibidi.txt", "a") as f:
		f.write("\n".join(sorted(result)) + "\n")
		f.write("PAS BELASTER FILE.\n")
	print(BashCompleterCase.TARGETS_OPTIONS.value)
	print("\n".join(sorted(result)))
	exit(RETURN_CODE_OK)



# Create application context and bind it.
context = ApplicationContext()
ApplicationContextBinder.application_context = context


with MuteStdout():
	# Load User's Belaster file.
	ubm = import_belaster_file(path=belaster_path)



targets = [ p.id for p in context.all_targets ]


with open("flibidi.txt", "a") as f:
	f.write("--------flop----------------\n" + "\n".join(targets) + "\n--------------\n")


result += targets


print(BashCompleterCase.TARGETS_OPTIONS.value)
print("\n".join(sorted(result)))


with open("flibidi.txt", "a") as f:
	f.write("--------result----------------\n" + "\n".join(sorted(result)) + "\n--------------\n")


exit(RETURN_CODE_OK)
